# Generated by Django 3.0.1 on 2019-12-30 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('place', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=2083)),
                ('image_url', models.CharField(max_length=2083)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('place', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=2083)),
                ('image_url2', models.CharField(max_length=2083)),
            ],
        ),
        migrations.CreateModel(
            name='Technical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('place', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=2083)),
                ('image_url', models.CharField(max_length=2083)),
            ],
        ),
    ]
